ansible_user: ubuntu
ansible_become: true

groups_fixed:
  - {name: "developers", gid: 23001 }
  - {name: "admins", gid: 23002 }

users_create:
  - name: "developer1"
    groups: ["developers", "docker"]
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEWoNE8+5MuIrCUm3RxFY5kohA8oSaAV04N7rfKOULOc dev1@desktop"
  - name: "admin1"
    groups: ["admins", "docker"]
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGS10IHQzwZCbGVAPgPsdyNIaXgNW9oHmDZ/nioCwVbx admin1@decktop"

sudo_nopasswd_group: "admins"
